# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  serviceconnection: 'sc-azure-hinault TP 3'


jobs:
  - job: 'Build'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restauration des packages NuGet'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    
    - task : DotNetCoreCLI@2
      displayName: 'Génération de la solution'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--confirguration $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: 'Excusion des test unitaires'
      inputs:
        command: 'test'
        projects: '**/*.UniTest.csproj'
        arguments: '--confirguration $(buildConfiguration)'
    